### ISSUE TITLE
content card alignment breaks on width transition

### ISSUE THREAD

**Issue by neorxna** [UoA-eResearch/research-hub-web#14]
Cards on content item page break alignment after transitioning from large to medium width.
However, the alignment does not break from small to medium or when starting at medium.

e.g.:
![image](https://user-images.githubusercontent.com/26913568/42199323-01c0389c-7ee2-11e8-850a-483ae8c1cdb3.png)

https://research-hub.auckland.ac.nz/#/content/3

**Comment by Hganavak** [comment]
Angular Material updates seem to have fixed this :man_shrugging: :+1:
