### ISSUE TITLE
browser autofill incorrectly uses email in fields for lastname and username 

### ISSUE THREAD

**Issue by akea013** [UoA-eResearch/research-hub-web#44]
Chrome and safari both incorrectly autofill email in fields
*  lastName
*  username 
of  __first__ entry in  Project members list on page 2 of form. 
 (floatLabel="never" setting means no label is present on autofill to guide form-filling).
Subsequent entries not autofilled, label present .  No errors.

Screenshot:
![autofill_errors](https://user-images.githubusercontent.com/34631537/62174927-cea31400-b38f-11e9-99a3-61234578c010.png)

Three recent tickets with these errors:
1)  REQ1167372: https://uoaprod.service-now.com/nav_to.do?uri=task.do?sys_id=e3efa565dbeebf44b975456a3a961915
2)  REQ1168866: https://uoaprod.service-now.com/nav_to.do?uri=task.do?sys_id=b921e040dbb2bb40b975456a3a961980
3)  REQ1167172: https://uoaprod.service-now.com/nav_to.do?uri=task.do?sys_id=7c1bfc9ddbeebb44b975456a3a96193f

**Comment by Hganavak** [comment]
* Fix deployed to production, see https://github.com/UoA-eResearch/research-hub-web/pull/46

**Comment by akea013** [comment]
Tiny fix to a not insignificant problem!  Thank you.
