### ISSUE TITLE
Data Owner and Data Contact fields mandatory

### ISSUE THREAD

**Issue by akea013** [UoA-eResearch/research-hub-web#53]
Currently, the form can be submitted with no team member assigned either of the roles 
* Data Owner
* Data Contact

Per storage request, we need 
*  at least one Data Owner, and they must be staff (not student)
* at least one Data Contact.

Perhaps there could be information posted on the form to say that if the role of  Data Contact 
 is not specified, it will be assigned to the Data Owner.

**Comment by akea013** [comment]
an update, addressing the hidden role of Project Owner which complicates these requirements (April 16)

> The form should require that three roles be specified as well as Team Members:
> 
> 1) Data Owner - mandatory, may be multiple, no restrictions
> 2) Data Contact - mandatory, may be multiple, no restrictions
> 3) Project Owner - mandatory, only one, must be staff.
> (If person completing the form is a student, this must be their supervisor).
> 
> The form should state:
> Data Contact will be contacted regarding allocation maintenance issues.
> Project Owner will be contacted  if there are any problems with the use of the allocation.
> 
> In addition, rather than requiring all of {name, upi, email} for all associated persons associated with the allocation, require only a university email. 
> (The rest can be obtained from LDAP when the request is processed.)

**Comment by akea013** [comment]
Addendum:  Please state on the  form that the email address should end with either
auckland.ac.nz or aucklanduni.ac.nz .  Could this be validated before form submission (javascript)?

**Comment by akea013** [comment]
re-open - accidentally closed

**Comment by mondkaefer** [comment]
Just checking in, because this change will likely help us getting rid of a lot of follow-ups with researchers on storage request tickets: Do you have a rough estimate on this one?

**Comment by warrickct** [comment]
Hey, the roughest estimate we have is by the end of next week we're hoping to have something live.

**Comment by warrickct** [comment]
Issues solved in commit 50818c001cf13affab13f4a7c7e4cc7f948500fc
