### ISSUE TITLE
Changes to the Nectar Research Cloud service page

### ISSUE THREAD

**Issue by mondkaefer** [UoA-eResearch/research-hub-web#54]
Hi team,

Please do a few changes to the Nectar Research Cloud service page (https://research-hub.auckland.ac.nz/#/content/70):

1. In addition to Sean Matheny, please add Jason He and Martin Feller as support contacts.

2. Please link the following page under "Policies": https://wiki.auckland.ac.nz/display/APPLCTN/Nectar+at+UoA+-+Data+Sovereignty+and+Security.

(I'm aware that this is not really a policy, but that location seems the best fit. Happy to discuss)

3. Please change the first paragraph in the Overview section as follows:

Change

> The University of Auckland is undertaking a pilot programme to provide a New Zealand hosted research cloud based on the Australian National eResearch Collaboration Tools and Resources ([Nectar](https://nectar.org.au/)) approach.

to 

> The University of Auckland is a partner of the Australian National eResearch Collaboration Tools and Resources ([Nectar](https://nectar.org.au/)) initiative, also known as the Nectar Research Cloud, to provide New Zealand hosted research cloud services to researchers of the University of Auckland.

Thanks,
Martin

**Comment by Hganavak** [comment]
All requested changes made. Thanks @mondkaefer :+1:
